version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/:/var/www/laravel
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/laravel

  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - ./docker/mysql/mysql.env
    volumes:
      - db_data:/var/lib/mysql

  composer:
    build:
      context: ./docker/php
      dockerfile: composer.Dockerfile
    volumes:
      - ./src/:/var/www/laravel

  artisan:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data: